### PR TITLE
Add ember-a11y team.

### PR DESCRIPTION
**Pull request by nathanhammond**
This is a forked core-notes repo for the ember-a11y team. All of our meeting notes will land here. As such we will operate the same way as the official teams while still being a community team. Keeping to standard formats, however, will make it easy to repatriate all of our information if we become adopted in the future. :smile:

### CODE REVIEW

**Comment by nathanhammond** [comment]
4/13 notes here for review–please respond with reactions to this post. Will be merged without objection when one of us remembers. 😄

/cc @noopkat @binhums @Robdel12 @MelSumner

**Comment by ghost** [comment]
You're a demon, looks good.

**Comment by noopkat** [comment]
one small question. I may have seemed a bit vague in the eyes when we were talking about `ember-a11y-testing` and `ember-aXe`. You meant renaming the current `ember-aXe` to now be `ember-a11y-testing` when it gets moved over to this org, do I have this right?

**Comment by trentmwillis** [comment]
@noopkat you are correct, I'll be handling that eventually. Been swamped with other work, but I plan to get my testing efforts for a11y joined in with this effort.

I plan to deprecate the current `ember-a11y-testing` addon and rename `ember-axe` to be `ember-a11y-testing` under this org.

**Comment by noopkat** [comment]
@trentmwillis thanks, just wanted to make sure I was on the same page!
@nathanhammond this all LGTM.

**Pull request merged**
